name: CI Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Mensagem 1"
        run: echo "Executando pipeline"

      - name: "Mensagem 2"
        run: echo "Pipeline finalizada"
      
    


